// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CSEBase.proto

#ifndef PROTOBUF_CSEBase_2eproto__INCLUDED
#define PROTOBUF_CSEBase_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "google/protobuf/timestamp.pb.h"
#include "CommonTypes.pb.h"
// @@protoc_insertion_point(includes)

namespace MicroWireless {
namespace OneM2M {
namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_CSEBase_2eproto();
void protobuf_AssignDesc_CSEBase_2eproto();
void protobuf_ShutdownFile_CSEBase_2eproto();

class CSEBase;

// ===================================================================

class CSEBase : public ::google::protobuf::Message {
 public:
  CSEBase();
  virtual ~CSEBase();

  CSEBase(const CSEBase& from);

  inline CSEBase& operator=(const CSEBase& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSEBase& default_instance();

  void Swap(CSEBase* other);

  // implements Message ----------------------------------------------

  inline CSEBase* New() const { return New(NULL); }

  CSEBase* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSEBase& from);
  void MergeFrom(const CSEBase& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CSEBase* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MicroWireless.OneM2M.pb.CommonTypes.ResourceType ty = 1;
  void clear_ty();
  static const int kTyFieldNumber = 1;
  ::MicroWireless::OneM2M::pb::CommonTypes_ResourceType ty() const;
  void set_ty(::MicroWireless::OneM2M::pb::CommonTypes_ResourceType value);

  // optional string ri = 2;
  void clear_ri();
  static const int kRiFieldNumber = 2;
  const ::std::string& ri() const;
  void set_ri(const ::std::string& value);
  void set_ri(const char* value);
  void set_ri(const char* value, size_t size);
  ::std::string* mutable_ri();
  ::std::string* release_ri();
  void set_allocated_ri(::std::string* ri);

  // optional string rn = 3;
  void clear_rn();
  static const int kRnFieldNumber = 3;
  const ::std::string& rn() const;
  void set_rn(const ::std::string& value);
  void set_rn(const char* value);
  void set_rn(const char* value, size_t size);
  ::std::string* mutable_rn();
  ::std::string* release_rn();
  void set_allocated_rn(::std::string* rn);

  // optional .google.protobuf.Timestamp ct = 5;
  bool has_ct() const;
  void clear_ct();
  static const int kCtFieldNumber = 5;
  const ::google::protobuf::Timestamp& ct() const;
  ::google::protobuf::Timestamp* mutable_ct();
  ::google::protobuf::Timestamp* release_ct();
  void set_allocated_ct(::google::protobuf::Timestamp* ct);

  // optional .google.protobuf.Timestamp lt = 6;
  bool has_lt() const;
  void clear_lt();
  static const int kLtFieldNumber = 6;
  const ::google::protobuf::Timestamp& lt() const;
  ::google::protobuf::Timestamp* mutable_lt();
  ::google::protobuf::Timestamp* release_lt();
  void set_allocated_lt(::google::protobuf::Timestamp* lt);

  // repeated string acpi = 7;
  int acpi_size() const;
  void clear_acpi();
  static const int kAcpiFieldNumber = 7;
  const ::std::string& acpi(int index) const;
  ::std::string* mutable_acpi(int index);
  void set_acpi(int index, const ::std::string& value);
  void set_acpi(int index, const char* value);
  void set_acpi(int index, const char* value, size_t size);
  ::std::string* add_acpi();
  void add_acpi(const ::std::string& value);
  void add_acpi(const char* value);
  void add_acpi(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& acpi() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_acpi();

  // repeated string lbl = 8;
  int lbl_size() const;
  void clear_lbl();
  static const int kLblFieldNumber = 8;
  const ::std::string& lbl(int index) const;
  ::std::string* mutable_lbl(int index);
  void set_lbl(int index, const ::std::string& value);
  void set_lbl(int index, const char* value);
  void set_lbl(int index, const char* value, size_t size);
  ::std::string* add_lbl();
  void add_lbl(const ::std::string& value);
  void add_lbl(const char* value);
  void add_lbl(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& lbl() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_lbl();

  // optional .MicroWireless.OneM2M.pb.CommonTypes.CSEType cst = 100;
  void clear_cst();
  static const int kCstFieldNumber = 100;
  ::MicroWireless::OneM2M::pb::CommonTypes_CSEType cst() const;
  void set_cst(::MicroWireless::OneM2M::pb::CommonTypes_CSEType value);

  // optional string csi = 101;
  void clear_csi();
  static const int kCsiFieldNumber = 101;
  const ::std::string& csi() const;
  void set_csi(const ::std::string& value);
  void set_csi(const char* value);
  void set_csi(const char* value, size_t size);
  ::std::string* mutable_csi();
  ::std::string* release_csi();
  void set_allocated_csi(::std::string* csi);

  // repeated .MicroWireless.OneM2M.pb.CommonTypes.SupportedResourceType srt = 102;
  int srt_size() const;
  void clear_srt();
  static const int kSrtFieldNumber = 102;
  ::MicroWireless::OneM2M::pb::CommonTypes_SupportedResourceType srt(int index) const;
  void set_srt(int index, ::MicroWireless::OneM2M::pb::CommonTypes_SupportedResourceType value);
  void add_srt(::MicroWireless::OneM2M::pb::CommonTypes_SupportedResourceType value);
  const ::google::protobuf::RepeatedField<int>& srt() const;
  ::google::protobuf::RepeatedField<int>* mutable_srt();

  // repeated .MicroWireless.OneM2M.pb.CommonTypes.PointOfAccess poa = 103;
  int poa_size() const;
  void clear_poa();
  static const int kPoaFieldNumber = 103;
  ::MicroWireless::OneM2M::pb::CommonTypes_PointOfAccess poa(int index) const;
  void set_poa(int index, ::MicroWireless::OneM2M::pb::CommonTypes_PointOfAccess value);
  void add_poa(::MicroWireless::OneM2M::pb::CommonTypes_PointOfAccess value);
  const ::google::protobuf::RepeatedField<int>& poa() const;
  ::google::protobuf::RepeatedField<int>* mutable_poa();

  // optional string nl = 104;
  void clear_nl();
  static const int kNlFieldNumber = 104;
  const ::std::string& nl() const;
  void set_nl(const ::std::string& value);
  void set_nl(const char* value);
  void set_nl(const char* value, size_t size);
  ::std::string* mutable_nl();
  ::std::string* release_nl();
  void set_allocated_nl(::std::string* nl);

  // optional string ncp = 105;
  void clear_ncp();
  static const int kNcpFieldNumber = 105;
  const ::std::string& ncp() const;
  void set_ncp(const ::std::string& value);
  void set_ncp(const char* value);
  void set_ncp(const char* value, size_t size);
  ::std::string* mutable_ncp();
  ::std::string* release_ncp();
  void set_allocated_ncp(::std::string* ncp);

  // @@protoc_insertion_point(class_scope:MicroWireless.OneM2M.pb.CSEBase)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr ri_;
  ::google::protobuf::internal::ArenaStringPtr rn_;
  ::google::protobuf::Timestamp* ct_;
  int ty_;
  int cst_;
  ::google::protobuf::Timestamp* lt_;
  ::google::protobuf::RepeatedPtrField< ::std::string> acpi_;
  ::google::protobuf::RepeatedPtrField< ::std::string> lbl_;
  ::google::protobuf::internal::ArenaStringPtr csi_;
  ::google::protobuf::RepeatedField<int> srt_;
  mutable int _srt_cached_byte_size_;
  ::google::protobuf::RepeatedField<int> poa_;
  mutable int _poa_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr nl_;
  ::google::protobuf::internal::ArenaStringPtr ncp_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_CSEBase_2eproto();
  friend void protobuf_AssignDesc_CSEBase_2eproto();
  friend void protobuf_ShutdownFile_CSEBase_2eproto();

  void InitAsDefaultInstance();
  static CSEBase* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CSEBase

// optional .MicroWireless.OneM2M.pb.CommonTypes.ResourceType ty = 1;
inline void CSEBase::clear_ty() {
  ty_ = 0;
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_ResourceType CSEBase::ty() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.ty)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_ResourceType >(ty_);
}
inline void CSEBase::set_ty(::MicroWireless::OneM2M::pb::CommonTypes_ResourceType value) {
  
  ty_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.CSEBase.ty)
}

// optional string ri = 2;
inline void CSEBase::clear_ri() {
  ri_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CSEBase::ri() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.ri)
  return ri_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSEBase::set_ri(const ::std::string& value) {
  
  ri_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.CSEBase.ri)
}
inline void CSEBase::set_ri(const char* value) {
  
  ri_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.CSEBase.ri)
}
inline void CSEBase::set_ri(const char* value, size_t size) {
  
  ri_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.CSEBase.ri)
}
inline ::std::string* CSEBase::mutable_ri() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.CSEBase.ri)
  return ri_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CSEBase::release_ri() {
  
  return ri_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSEBase::set_allocated_ri(::std::string* ri) {
  if (ri != NULL) {
    
  } else {
    
  }
  ri_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ri);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.CSEBase.ri)
}

// optional string rn = 3;
inline void CSEBase::clear_rn() {
  rn_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CSEBase::rn() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.rn)
  return rn_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSEBase::set_rn(const ::std::string& value) {
  
  rn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.CSEBase.rn)
}
inline void CSEBase::set_rn(const char* value) {
  
  rn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.CSEBase.rn)
}
inline void CSEBase::set_rn(const char* value, size_t size) {
  
  rn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.CSEBase.rn)
}
inline ::std::string* CSEBase::mutable_rn() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.CSEBase.rn)
  return rn_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CSEBase::release_rn() {
  
  return rn_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSEBase::set_allocated_rn(::std::string* rn) {
  if (rn != NULL) {
    
  } else {
    
  }
  rn_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rn);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.CSEBase.rn)
}

// optional .google.protobuf.Timestamp ct = 5;
inline bool CSEBase::has_ct() const {
  return !_is_default_instance_ && ct_ != NULL;
}
inline void CSEBase::clear_ct() {
  if (GetArenaNoVirtual() == NULL && ct_ != NULL) delete ct_;
  ct_ = NULL;
}
inline const ::google::protobuf::Timestamp& CSEBase::ct() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.ct)
  return ct_ != NULL ? *ct_ : *default_instance_->ct_;
}
inline ::google::protobuf::Timestamp* CSEBase::mutable_ct() {
  
  if (ct_ == NULL) {
    ct_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.CSEBase.ct)
  return ct_;
}
inline ::google::protobuf::Timestamp* CSEBase::release_ct() {
  
  ::google::protobuf::Timestamp* temp = ct_;
  ct_ = NULL;
  return temp;
}
inline void CSEBase::set_allocated_ct(::google::protobuf::Timestamp* ct) {
  delete ct_;
  ct_ = ct;
  if (ct) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.CSEBase.ct)
}

// optional .google.protobuf.Timestamp lt = 6;
inline bool CSEBase::has_lt() const {
  return !_is_default_instance_ && lt_ != NULL;
}
inline void CSEBase::clear_lt() {
  if (GetArenaNoVirtual() == NULL && lt_ != NULL) delete lt_;
  lt_ = NULL;
}
inline const ::google::protobuf::Timestamp& CSEBase::lt() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.lt)
  return lt_ != NULL ? *lt_ : *default_instance_->lt_;
}
inline ::google::protobuf::Timestamp* CSEBase::mutable_lt() {
  
  if (lt_ == NULL) {
    lt_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.CSEBase.lt)
  return lt_;
}
inline ::google::protobuf::Timestamp* CSEBase::release_lt() {
  
  ::google::protobuf::Timestamp* temp = lt_;
  lt_ = NULL;
  return temp;
}
inline void CSEBase::set_allocated_lt(::google::protobuf::Timestamp* lt) {
  delete lt_;
  lt_ = lt;
  if (lt) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.CSEBase.lt)
}

// repeated string acpi = 7;
inline int CSEBase::acpi_size() const {
  return acpi_.size();
}
inline void CSEBase::clear_acpi() {
  acpi_.Clear();
}
inline const ::std::string& CSEBase::acpi(int index) const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.acpi)
  return acpi_.Get(index);
}
inline ::std::string* CSEBase::mutable_acpi(int index) {
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.CSEBase.acpi)
  return acpi_.Mutable(index);
}
inline void CSEBase::set_acpi(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.CSEBase.acpi)
  acpi_.Mutable(index)->assign(value);
}
inline void CSEBase::set_acpi(int index, const char* value) {
  acpi_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.CSEBase.acpi)
}
inline void CSEBase::set_acpi(int index, const char* value, size_t size) {
  acpi_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.CSEBase.acpi)
}
inline ::std::string* CSEBase::add_acpi() {
  return acpi_.Add();
}
inline void CSEBase::add_acpi(const ::std::string& value) {
  acpi_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:MicroWireless.OneM2M.pb.CSEBase.acpi)
}
inline void CSEBase::add_acpi(const char* value) {
  acpi_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:MicroWireless.OneM2M.pb.CSEBase.acpi)
}
inline void CSEBase::add_acpi(const char* value, size_t size) {
  acpi_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:MicroWireless.OneM2M.pb.CSEBase.acpi)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
CSEBase::acpi() const {
  // @@protoc_insertion_point(field_list:MicroWireless.OneM2M.pb.CSEBase.acpi)
  return acpi_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
CSEBase::mutable_acpi() {
  // @@protoc_insertion_point(field_mutable_list:MicroWireless.OneM2M.pb.CSEBase.acpi)
  return &acpi_;
}

// repeated string lbl = 8;
inline int CSEBase::lbl_size() const {
  return lbl_.size();
}
inline void CSEBase::clear_lbl() {
  lbl_.Clear();
}
inline const ::std::string& CSEBase::lbl(int index) const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.lbl)
  return lbl_.Get(index);
}
inline ::std::string* CSEBase::mutable_lbl(int index) {
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.CSEBase.lbl)
  return lbl_.Mutable(index);
}
inline void CSEBase::set_lbl(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.CSEBase.lbl)
  lbl_.Mutable(index)->assign(value);
}
inline void CSEBase::set_lbl(int index, const char* value) {
  lbl_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.CSEBase.lbl)
}
inline void CSEBase::set_lbl(int index, const char* value, size_t size) {
  lbl_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.CSEBase.lbl)
}
inline ::std::string* CSEBase::add_lbl() {
  return lbl_.Add();
}
inline void CSEBase::add_lbl(const ::std::string& value) {
  lbl_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:MicroWireless.OneM2M.pb.CSEBase.lbl)
}
inline void CSEBase::add_lbl(const char* value) {
  lbl_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:MicroWireless.OneM2M.pb.CSEBase.lbl)
}
inline void CSEBase::add_lbl(const char* value, size_t size) {
  lbl_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:MicroWireless.OneM2M.pb.CSEBase.lbl)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
CSEBase::lbl() const {
  // @@protoc_insertion_point(field_list:MicroWireless.OneM2M.pb.CSEBase.lbl)
  return lbl_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
CSEBase::mutable_lbl() {
  // @@protoc_insertion_point(field_mutable_list:MicroWireless.OneM2M.pb.CSEBase.lbl)
  return &lbl_;
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.CSEType cst = 100;
inline void CSEBase::clear_cst() {
  cst_ = 0;
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_CSEType CSEBase::cst() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.cst)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_CSEType >(cst_);
}
inline void CSEBase::set_cst(::MicroWireless::OneM2M::pb::CommonTypes_CSEType value) {
  
  cst_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.CSEBase.cst)
}

// optional string csi = 101;
inline void CSEBase::clear_csi() {
  csi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CSEBase::csi() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.csi)
  return csi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSEBase::set_csi(const ::std::string& value) {
  
  csi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.CSEBase.csi)
}
inline void CSEBase::set_csi(const char* value) {
  
  csi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.CSEBase.csi)
}
inline void CSEBase::set_csi(const char* value, size_t size) {
  
  csi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.CSEBase.csi)
}
inline ::std::string* CSEBase::mutable_csi() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.CSEBase.csi)
  return csi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CSEBase::release_csi() {
  
  return csi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSEBase::set_allocated_csi(::std::string* csi) {
  if (csi != NULL) {
    
  } else {
    
  }
  csi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), csi);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.CSEBase.csi)
}

// repeated .MicroWireless.OneM2M.pb.CommonTypes.SupportedResourceType srt = 102;
inline int CSEBase::srt_size() const {
  return srt_.size();
}
inline void CSEBase::clear_srt() {
  srt_.Clear();
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_SupportedResourceType CSEBase::srt(int index) const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.srt)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_SupportedResourceType >(srt_.Get(index));
}
inline void CSEBase::set_srt(int index, ::MicroWireless::OneM2M::pb::CommonTypes_SupportedResourceType value) {
  srt_.Set(index, value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.CSEBase.srt)
}
inline void CSEBase::add_srt(::MicroWireless::OneM2M::pb::CommonTypes_SupportedResourceType value) {
  srt_.Add(value);
  // @@protoc_insertion_point(field_add:MicroWireless.OneM2M.pb.CSEBase.srt)
}
inline const ::google::protobuf::RepeatedField<int>&
CSEBase::srt() const {
  // @@protoc_insertion_point(field_list:MicroWireless.OneM2M.pb.CSEBase.srt)
  return srt_;
}
inline ::google::protobuf::RepeatedField<int>*
CSEBase::mutable_srt() {
  // @@protoc_insertion_point(field_mutable_list:MicroWireless.OneM2M.pb.CSEBase.srt)
  return &srt_;
}

// repeated .MicroWireless.OneM2M.pb.CommonTypes.PointOfAccess poa = 103;
inline int CSEBase::poa_size() const {
  return poa_.size();
}
inline void CSEBase::clear_poa() {
  poa_.Clear();
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_PointOfAccess CSEBase::poa(int index) const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.poa)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_PointOfAccess >(poa_.Get(index));
}
inline void CSEBase::set_poa(int index, ::MicroWireless::OneM2M::pb::CommonTypes_PointOfAccess value) {
  poa_.Set(index, value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.CSEBase.poa)
}
inline void CSEBase::add_poa(::MicroWireless::OneM2M::pb::CommonTypes_PointOfAccess value) {
  poa_.Add(value);
  // @@protoc_insertion_point(field_add:MicroWireless.OneM2M.pb.CSEBase.poa)
}
inline const ::google::protobuf::RepeatedField<int>&
CSEBase::poa() const {
  // @@protoc_insertion_point(field_list:MicroWireless.OneM2M.pb.CSEBase.poa)
  return poa_;
}
inline ::google::protobuf::RepeatedField<int>*
CSEBase::mutable_poa() {
  // @@protoc_insertion_point(field_mutable_list:MicroWireless.OneM2M.pb.CSEBase.poa)
  return &poa_;
}

// optional string nl = 104;
inline void CSEBase::clear_nl() {
  nl_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CSEBase::nl() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.nl)
  return nl_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSEBase::set_nl(const ::std::string& value) {
  
  nl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.CSEBase.nl)
}
inline void CSEBase::set_nl(const char* value) {
  
  nl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.CSEBase.nl)
}
inline void CSEBase::set_nl(const char* value, size_t size) {
  
  nl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.CSEBase.nl)
}
inline ::std::string* CSEBase::mutable_nl() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.CSEBase.nl)
  return nl_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CSEBase::release_nl() {
  
  return nl_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSEBase::set_allocated_nl(::std::string* nl) {
  if (nl != NULL) {
    
  } else {
    
  }
  nl_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nl);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.CSEBase.nl)
}

// optional string ncp = 105;
inline void CSEBase::clear_ncp() {
  ncp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CSEBase::ncp() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.CSEBase.ncp)
  return ncp_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSEBase::set_ncp(const ::std::string& value) {
  
  ncp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.CSEBase.ncp)
}
inline void CSEBase::set_ncp(const char* value) {
  
  ncp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.CSEBase.ncp)
}
inline void CSEBase::set_ncp(const char* value, size_t size) {
  
  ncp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.CSEBase.ncp)
}
inline ::std::string* CSEBase::mutable_ncp() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.CSEBase.ncp)
  return ncp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CSEBase::release_ncp() {
  
  return ncp_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSEBase::set_allocated_ncp(::std::string* ncp) {
  if (ncp != NULL) {
    
  } else {
    
  }
  ncp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ncp);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.CSEBase.ncp)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace OneM2M
}  // namespace MicroWireless

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CSEBase_2eproto__INCLUDED
