// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

#ifndef PROTOBUF_Request_2eproto__INCLUDED
#define PROTOBUF_Request_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "google/protobuf/timestamp.pb.h"
#include "google/protobuf/duration.pb.h"
#include "CommonTypes.pb.h"
// @@protoc_insertion_point(includes)

namespace MicroWireless {
namespace OneM2M {
namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Request_2eproto();
void protobuf_AssignDesc_Request_2eproto();
void protobuf_ShutdownFile_Request_2eproto();

class FilterCriteria;
class Request;

// ===================================================================

class FilterCriteria : public ::google::protobuf::Message {
 public:
  FilterCriteria();
  virtual ~FilterCriteria();

  FilterCriteria(const FilterCriteria& from);

  inline FilterCriteria& operator=(const FilterCriteria& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FilterCriteria& default_instance();

  void Swap(FilterCriteria* other);

  // implements Message ----------------------------------------------

  inline FilterCriteria* New() const { return New(NULL); }

  FilterCriteria* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FilterCriteria& from);
  void MergeFrom(const FilterCriteria& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FilterCriteria* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .google.protobuf.Timestamp crb = 1;
  bool has_crb() const;
  void clear_crb();
  static const int kCrbFieldNumber = 1;
  const ::google::protobuf::Timestamp& crb() const;
  ::google::protobuf::Timestamp* mutable_crb();
  ::google::protobuf::Timestamp* release_crb();
  void set_allocated_crb(::google::protobuf::Timestamp* crb);

  // optional .google.protobuf.Timestamp cra = 2;
  bool has_cra() const;
  void clear_cra();
  static const int kCraFieldNumber = 2;
  const ::google::protobuf::Timestamp& cra() const;
  ::google::protobuf::Timestamp* mutable_cra();
  ::google::protobuf::Timestamp* release_cra();
  void set_allocated_cra(::google::protobuf::Timestamp* cra);

  // optional .google.protobuf.Timestamp ms = 3;
  bool has_ms() const;
  void clear_ms();
  static const int kMsFieldNumber = 3;
  const ::google::protobuf::Timestamp& ms() const;
  ::google::protobuf::Timestamp* mutable_ms();
  ::google::protobuf::Timestamp* release_ms();
  void set_allocated_ms(::google::protobuf::Timestamp* ms);

  // optional .google.protobuf.Timestamp us = 4;
  bool has_us() const;
  void clear_us();
  static const int kUsFieldNumber = 4;
  const ::google::protobuf::Timestamp& us() const;
  ::google::protobuf::Timestamp* mutable_us();
  ::google::protobuf::Timestamp* release_us();
  void set_allocated_us(::google::protobuf::Timestamp* us);

  // optional uint32 sts = 5;
  void clear_sts();
  static const int kStsFieldNumber = 5;
  ::google::protobuf::uint32 sts() const;
  void set_sts(::google::protobuf::uint32 value);

  // optional uint32 stb = 6;
  void clear_stb();
  static const int kStbFieldNumber = 6;
  ::google::protobuf::uint32 stb() const;
  void set_stb(::google::protobuf::uint32 value);

  // optional .google.protobuf.Timestamp exb = 7;
  bool has_exb() const;
  void clear_exb();
  static const int kExbFieldNumber = 7;
  const ::google::protobuf::Timestamp& exb() const;
  ::google::protobuf::Timestamp* mutable_exb();
  ::google::protobuf::Timestamp* release_exb();
  void set_allocated_exb(::google::protobuf::Timestamp* exb);

  // optional .google.protobuf.Timestamp exa = 8;
  bool has_exa() const;
  void clear_exa();
  static const int kExaFieldNumber = 8;
  const ::google::protobuf::Timestamp& exa() const;
  ::google::protobuf::Timestamp* mutable_exa();
  ::google::protobuf::Timestamp* release_exa();
  void set_allocated_exa(::google::protobuf::Timestamp* exa);

  // repeated string lbl = 9;
  int lbl_size() const;
  void clear_lbl();
  static const int kLblFieldNumber = 9;
  const ::std::string& lbl(int index) const;
  ::std::string* mutable_lbl(int index);
  void set_lbl(int index, const ::std::string& value);
  void set_lbl(int index, const char* value);
  void set_lbl(int index, const char* value, size_t size);
  ::std::string* add_lbl();
  void add_lbl(const ::std::string& value);
  void add_lbl(const char* value);
  void add_lbl(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& lbl() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_lbl();

  // repeated .MicroWireless.OneM2M.pb.CommonTypes.ResourceType rty = 10;
  int rty_size() const;
  void clear_rty();
  static const int kRtyFieldNumber = 10;
  ::MicroWireless::OneM2M::pb::CommonTypes_ResourceType rty(int index) const;
  void set_rty(int index, ::MicroWireless::OneM2M::pb::CommonTypes_ResourceType value);
  void add_rty(::MicroWireless::OneM2M::pb::CommonTypes_ResourceType value);
  const ::google::protobuf::RepeatedField<int>& rty() const;
  ::google::protobuf::RepeatedField<int>* mutable_rty();

  // optional uint64 sza = 11;
  void clear_sza();
  static const int kSzaFieldNumber = 11;
  ::google::protobuf::uint64 sza() const;
  void set_sza(::google::protobuf::uint64 value);

  // optional uint64 szb = 12;
  void clear_szb();
  static const int kSzbFieldNumber = 12;
  ::google::protobuf::uint64 szb() const;
  void set_szb(::google::protobuf::uint64 value);

  // repeated .MicroWireless.OneM2M.pb.CommonTypes.ContentType cty = 13;
  int cty_size() const;
  void clear_cty();
  static const int kCtyFieldNumber = 13;
  ::MicroWireless::OneM2M::pb::CommonTypes_ContentType cty(int index) const;
  void set_cty(int index, ::MicroWireless::OneM2M::pb::CommonTypes_ContentType value);
  void add_cty(::MicroWireless::OneM2M::pb::CommonTypes_ContentType value);
  const ::google::protobuf::RepeatedField<int>& cty() const;
  ::google::protobuf::RepeatedField<int>* mutable_cty();

  // repeated .MicroWireless.OneM2M.pb.Attribute atr = 14;
  int atr_size() const;
  void clear_atr();
  static const int kAtrFieldNumber = 14;
  const ::MicroWireless::OneM2M::pb::Attribute& atr(int index) const;
  ::MicroWireless::OneM2M::pb::Attribute* mutable_atr(int index);
  ::MicroWireless::OneM2M::pb::Attribute* add_atr();
  const ::google::protobuf::RepeatedPtrField< ::MicroWireless::OneM2M::pb::Attribute >&
      atr() const;
  ::google::protobuf::RepeatedPtrField< ::MicroWireless::OneM2M::pb::Attribute >*
      mutable_atr();

  // optional .MicroWireless.OneM2M.pb.CommonTypes.FilterUsage fu = 15;
  void clear_fu();
  static const int kFuFieldNumber = 15;
  ::MicroWireless::OneM2M::pb::CommonTypes_FilterUsage fu() const;
  void set_fu(::MicroWireless::OneM2M::pb::CommonTypes_FilterUsage value);

  // optional uint32 lim = 16;
  void clear_lim();
  static const int kLimFieldNumber = 16;
  ::google::protobuf::uint32 lim() const;
  void set_lim(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MicroWireless.OneM2M.pb.FilterCriteria)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::Timestamp* crb_;
  ::google::protobuf::Timestamp* cra_;
  ::google::protobuf::Timestamp* ms_;
  ::google::protobuf::Timestamp* us_;
  ::google::protobuf::uint32 sts_;
  ::google::protobuf::uint32 stb_;
  ::google::protobuf::Timestamp* exb_;
  ::google::protobuf::Timestamp* exa_;
  ::google::protobuf::RepeatedPtrField< ::std::string> lbl_;
  ::google::protobuf::RepeatedField<int> rty_;
  mutable int _rty_cached_byte_size_;
  ::google::protobuf::uint64 sza_;
  ::google::protobuf::uint64 szb_;
  ::google::protobuf::RepeatedField<int> cty_;
  mutable int _cty_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::MicroWireless::OneM2M::pb::Attribute > atr_;
  int fu_;
  ::google::protobuf::uint32 lim_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Request_2eproto();
  friend void protobuf_AssignDesc_Request_2eproto();
  friend void protobuf_ShutdownFile_Request_2eproto();

  void InitAsDefaultInstance();
  static FilterCriteria* default_instance_;
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  void Swap(Request* other);

  // implements Message ----------------------------------------------

  inline Request* New() const { return New(NULL); }

  Request* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MicroWireless.OneM2M.pb.CommonTypes.Operation op = 1;
  void clear_op();
  static const int kOpFieldNumber = 1;
  ::MicroWireless::OneM2M::pb::CommonTypes_Operation op() const;
  void set_op(::MicroWireless::OneM2M::pb::CommonTypes_Operation value);

  // optional string to = 2;
  void clear_to();
  static const int kToFieldNumber = 2;
  const ::std::string& to() const;
  void set_to(const ::std::string& value);
  void set_to(const char* value);
  void set_to(const char* value, size_t size);
  ::std::string* mutable_to();
  ::std::string* release_to();
  void set_allocated_to(::std::string* to);

  // optional string fr = 3;
  void clear_fr();
  static const int kFrFieldNumber = 3;
  const ::std::string& fr() const;
  void set_fr(const ::std::string& value);
  void set_fr(const char* value);
  void set_fr(const char* value, size_t size);
  ::std::string* mutable_fr();
  ::std::string* release_fr();
  void set_allocated_fr(::std::string* fr);

  // optional string rqi = 4;
  void clear_rqi();
  static const int kRqiFieldNumber = 4;
  const ::std::string& rqi() const;
  void set_rqi(const ::std::string& value);
  void set_rqi(const char* value);
  void set_rqi(const char* value, size_t size);
  ::std::string* mutable_rqi();
  ::std::string* release_rqi();
  void set_allocated_rqi(::std::string* rqi);

  // optional .MicroWireless.OneM2M.pb.CommonTypes.ResourceType ty = 5;
  void clear_ty();
  static const int kTyFieldNumber = 5;
  ::MicroWireless::OneM2M::pb::CommonTypes_ResourceType ty() const;
  void set_ty(::MicroWireless::OneM2M::pb::CommonTypes_ResourceType value);

  // optional string nm = 6;
  void clear_nm();
  static const int kNmFieldNumber = 6;
  const ::std::string& nm() const;
  void set_nm(const ::std::string& value);
  void set_nm(const char* value);
  void set_nm(const char* value, size_t size);
  ::std::string* mutable_nm();
  ::std::string* release_nm();
  void set_allocated_nm(::std::string* nm);

  // optional string pc = 7;
  void clear_pc();
  static const int kPcFieldNumber = 7;
  const ::std::string& pc() const;
  void set_pc(const ::std::string& value);
  void set_pc(const char* value);
  void set_pc(const char* value, size_t size);
  ::std::string* mutable_pc();
  ::std::string* release_pc();
  void set_allocated_pc(::std::string* pc);

  // optional .google.protobuf.Timestamp ot = 8;
  bool has_ot() const;
  void clear_ot();
  static const int kOtFieldNumber = 8;
  const ::google::protobuf::Timestamp& ot() const;
  ::google::protobuf::Timestamp* mutable_ot();
  ::google::protobuf::Timestamp* release_ot();
  void set_allocated_ot(::google::protobuf::Timestamp* ot);

  // optional .google.protobuf.Timestamp rqet = 9;
  bool has_rqet() const;
  void clear_rqet();
  static const int kRqetFieldNumber = 9;
  const ::google::protobuf::Timestamp& rqet() const;
  ::google::protobuf::Timestamp* mutable_rqet();
  ::google::protobuf::Timestamp* release_rqet();
  void set_allocated_rqet(::google::protobuf::Timestamp* rqet);

  // optional .google.protobuf.Timestamp rset = 10;
  bool has_rset() const;
  void clear_rset();
  static const int kRsetFieldNumber = 10;
  const ::google::protobuf::Timestamp& rset() const;
  ::google::protobuf::Timestamp* mutable_rset();
  ::google::protobuf::Timestamp* release_rset();
  void set_allocated_rset(::google::protobuf::Timestamp* rset);

  // optional .google.protobuf.Duration oet = 11;
  bool has_oet() const;
  void clear_oet();
  static const int kOetFieldNumber = 11;
  const ::google::protobuf::Duration& oet() const;
  ::google::protobuf::Duration* mutable_oet();
  ::google::protobuf::Duration* release_oet();
  void set_allocated_oet(::google::protobuf::Duration* oet);

  // optional .MicroWireless.OneM2M.pb.CommonTypes.ResponseType rt = 12;
  void clear_rt();
  static const int kRtFieldNumber = 12;
  ::MicroWireless::OneM2M::pb::CommonTypes_ResponseType rt() const;
  void set_rt(::MicroWireless::OneM2M::pb::CommonTypes_ResponseType value);

  // optional .google.protobuf.Duration rp = 13;
  bool has_rp() const;
  void clear_rp();
  static const int kRpFieldNumber = 13;
  const ::google::protobuf::Duration& rp() const;
  ::google::protobuf::Duration* mutable_rp();
  ::google::protobuf::Duration* release_rp();
  void set_allocated_rp(::google::protobuf::Duration* rp);

  // optional .MicroWireless.OneM2M.pb.CommonTypes.ResultContent rcn = 14;
  void clear_rcn();
  static const int kRcnFieldNumber = 14;
  ::MicroWireless::OneM2M::pb::CommonTypes_ResultContent rcn() const;
  void set_rcn(::MicroWireless::OneM2M::pb::CommonTypes_ResultContent value);

  // optional .MicroWireless.OneM2M.pb.CommonTypes.EventCat ec = 15;
  void clear_ec();
  static const int kEcFieldNumber = 15;
  ::MicroWireless::OneM2M::pb::CommonTypes_EventCat ec() const;
  void set_ec(::MicroWireless::OneM2M::pb::CommonTypes_EventCat value);

  // optional bool da = 16;
  void clear_da();
  static const int kDaFieldNumber = 16;
  bool da() const;
  void set_da(bool value);

  // optional string gid = 17;
  void clear_gid();
  static const int kGidFieldNumber = 17;
  const ::std::string& gid() const;
  void set_gid(const ::std::string& value);
  void set_gid(const char* value);
  void set_gid(const char* value, size_t size);
  ::std::string* mutable_gid();
  ::std::string* release_gid();
  void set_allocated_gid(::std::string* gid);

  // optional .MicroWireless.OneM2M.pb.FilterCriteria fc = 18;
  bool has_fc() const;
  void clear_fc();
  static const int kFcFieldNumber = 18;
  const ::MicroWireless::OneM2M::pb::FilterCriteria& fc() const;
  ::MicroWireless::OneM2M::pb::FilterCriteria* mutable_fc();
  ::MicroWireless::OneM2M::pb::FilterCriteria* release_fc();
  void set_allocated_fc(::MicroWireless::OneM2M::pb::FilterCriteria* fc);

  // optional .MicroWireless.OneM2M.pb.CommonTypes.DiscoveryResultType drt = 19;
  void clear_drt();
  static const int kDrtFieldNumber = 19;
  ::MicroWireless::OneM2M::pb::CommonTypes_DiscoveryResultType drt() const;
  void set_drt(::MicroWireless::OneM2M::pb::CommonTypes_DiscoveryResultType value);

  // @@protoc_insertion_point(class_scope:MicroWireless.OneM2M.pb.Request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr to_;
  ::google::protobuf::internal::ArenaStringPtr fr_;
  int op_;
  int ty_;
  ::google::protobuf::internal::ArenaStringPtr rqi_;
  ::google::protobuf::internal::ArenaStringPtr nm_;
  ::google::protobuf::internal::ArenaStringPtr pc_;
  ::google::protobuf::Timestamp* ot_;
  ::google::protobuf::Timestamp* rqet_;
  ::google::protobuf::Timestamp* rset_;
  ::google::protobuf::Duration* oet_;
  ::google::protobuf::Duration* rp_;
  int rt_;
  int rcn_;
  int ec_;
  bool da_;
  ::google::protobuf::internal::ArenaStringPtr gid_;
  ::MicroWireless::OneM2M::pb::FilterCriteria* fc_;
  int drt_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Request_2eproto();
  friend void protobuf_AssignDesc_Request_2eproto();
  friend void protobuf_ShutdownFile_Request_2eproto();

  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// FilterCriteria

// optional .google.protobuf.Timestamp crb = 1;
inline bool FilterCriteria::has_crb() const {
  return !_is_default_instance_ && crb_ != NULL;
}
inline void FilterCriteria::clear_crb() {
  if (GetArenaNoVirtual() == NULL && crb_ != NULL) delete crb_;
  crb_ = NULL;
}
inline const ::google::protobuf::Timestamp& FilterCriteria::crb() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.crb)
  return crb_ != NULL ? *crb_ : *default_instance_->crb_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::mutable_crb() {
  
  if (crb_ == NULL) {
    crb_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.FilterCriteria.crb)
  return crb_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::release_crb() {
  
  ::google::protobuf::Timestamp* temp = crb_;
  crb_ = NULL;
  return temp;
}
inline void FilterCriteria::set_allocated_crb(::google::protobuf::Timestamp* crb) {
  delete crb_;
  crb_ = crb;
  if (crb) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.FilterCriteria.crb)
}

// optional .google.protobuf.Timestamp cra = 2;
inline bool FilterCriteria::has_cra() const {
  return !_is_default_instance_ && cra_ != NULL;
}
inline void FilterCriteria::clear_cra() {
  if (GetArenaNoVirtual() == NULL && cra_ != NULL) delete cra_;
  cra_ = NULL;
}
inline const ::google::protobuf::Timestamp& FilterCriteria::cra() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.cra)
  return cra_ != NULL ? *cra_ : *default_instance_->cra_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::mutable_cra() {
  
  if (cra_ == NULL) {
    cra_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.FilterCriteria.cra)
  return cra_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::release_cra() {
  
  ::google::protobuf::Timestamp* temp = cra_;
  cra_ = NULL;
  return temp;
}
inline void FilterCriteria::set_allocated_cra(::google::protobuf::Timestamp* cra) {
  delete cra_;
  cra_ = cra;
  if (cra) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.FilterCriteria.cra)
}

// optional .google.protobuf.Timestamp ms = 3;
inline bool FilterCriteria::has_ms() const {
  return !_is_default_instance_ && ms_ != NULL;
}
inline void FilterCriteria::clear_ms() {
  if (GetArenaNoVirtual() == NULL && ms_ != NULL) delete ms_;
  ms_ = NULL;
}
inline const ::google::protobuf::Timestamp& FilterCriteria::ms() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.ms)
  return ms_ != NULL ? *ms_ : *default_instance_->ms_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::mutable_ms() {
  
  if (ms_ == NULL) {
    ms_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.FilterCriteria.ms)
  return ms_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::release_ms() {
  
  ::google::protobuf::Timestamp* temp = ms_;
  ms_ = NULL;
  return temp;
}
inline void FilterCriteria::set_allocated_ms(::google::protobuf::Timestamp* ms) {
  delete ms_;
  ms_ = ms;
  if (ms) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.FilterCriteria.ms)
}

// optional .google.protobuf.Timestamp us = 4;
inline bool FilterCriteria::has_us() const {
  return !_is_default_instance_ && us_ != NULL;
}
inline void FilterCriteria::clear_us() {
  if (GetArenaNoVirtual() == NULL && us_ != NULL) delete us_;
  us_ = NULL;
}
inline const ::google::protobuf::Timestamp& FilterCriteria::us() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.us)
  return us_ != NULL ? *us_ : *default_instance_->us_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::mutable_us() {
  
  if (us_ == NULL) {
    us_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.FilterCriteria.us)
  return us_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::release_us() {
  
  ::google::protobuf::Timestamp* temp = us_;
  us_ = NULL;
  return temp;
}
inline void FilterCriteria::set_allocated_us(::google::protobuf::Timestamp* us) {
  delete us_;
  us_ = us;
  if (us) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.FilterCriteria.us)
}

// optional uint32 sts = 5;
inline void FilterCriteria::clear_sts() {
  sts_ = 0u;
}
inline ::google::protobuf::uint32 FilterCriteria::sts() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.sts)
  return sts_;
}
inline void FilterCriteria::set_sts(::google::protobuf::uint32 value) {
  
  sts_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.FilterCriteria.sts)
}

// optional uint32 stb = 6;
inline void FilterCriteria::clear_stb() {
  stb_ = 0u;
}
inline ::google::protobuf::uint32 FilterCriteria::stb() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.stb)
  return stb_;
}
inline void FilterCriteria::set_stb(::google::protobuf::uint32 value) {
  
  stb_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.FilterCriteria.stb)
}

// optional .google.protobuf.Timestamp exb = 7;
inline bool FilterCriteria::has_exb() const {
  return !_is_default_instance_ && exb_ != NULL;
}
inline void FilterCriteria::clear_exb() {
  if (GetArenaNoVirtual() == NULL && exb_ != NULL) delete exb_;
  exb_ = NULL;
}
inline const ::google::protobuf::Timestamp& FilterCriteria::exb() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.exb)
  return exb_ != NULL ? *exb_ : *default_instance_->exb_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::mutable_exb() {
  
  if (exb_ == NULL) {
    exb_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.FilterCriteria.exb)
  return exb_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::release_exb() {
  
  ::google::protobuf::Timestamp* temp = exb_;
  exb_ = NULL;
  return temp;
}
inline void FilterCriteria::set_allocated_exb(::google::protobuf::Timestamp* exb) {
  delete exb_;
  exb_ = exb;
  if (exb) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.FilterCriteria.exb)
}

// optional .google.protobuf.Timestamp exa = 8;
inline bool FilterCriteria::has_exa() const {
  return !_is_default_instance_ && exa_ != NULL;
}
inline void FilterCriteria::clear_exa() {
  if (GetArenaNoVirtual() == NULL && exa_ != NULL) delete exa_;
  exa_ = NULL;
}
inline const ::google::protobuf::Timestamp& FilterCriteria::exa() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.exa)
  return exa_ != NULL ? *exa_ : *default_instance_->exa_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::mutable_exa() {
  
  if (exa_ == NULL) {
    exa_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.FilterCriteria.exa)
  return exa_;
}
inline ::google::protobuf::Timestamp* FilterCriteria::release_exa() {
  
  ::google::protobuf::Timestamp* temp = exa_;
  exa_ = NULL;
  return temp;
}
inline void FilterCriteria::set_allocated_exa(::google::protobuf::Timestamp* exa) {
  delete exa_;
  exa_ = exa;
  if (exa) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.FilterCriteria.exa)
}

// repeated string lbl = 9;
inline int FilterCriteria::lbl_size() const {
  return lbl_.size();
}
inline void FilterCriteria::clear_lbl() {
  lbl_.Clear();
}
inline const ::std::string& FilterCriteria::lbl(int index) const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.lbl)
  return lbl_.Get(index);
}
inline ::std::string* FilterCriteria::mutable_lbl(int index) {
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.FilterCriteria.lbl)
  return lbl_.Mutable(index);
}
inline void FilterCriteria::set_lbl(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.FilterCriteria.lbl)
  lbl_.Mutable(index)->assign(value);
}
inline void FilterCriteria::set_lbl(int index, const char* value) {
  lbl_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.FilterCriteria.lbl)
}
inline void FilterCriteria::set_lbl(int index, const char* value, size_t size) {
  lbl_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.FilterCriteria.lbl)
}
inline ::std::string* FilterCriteria::add_lbl() {
  return lbl_.Add();
}
inline void FilterCriteria::add_lbl(const ::std::string& value) {
  lbl_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:MicroWireless.OneM2M.pb.FilterCriteria.lbl)
}
inline void FilterCriteria::add_lbl(const char* value) {
  lbl_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:MicroWireless.OneM2M.pb.FilterCriteria.lbl)
}
inline void FilterCriteria::add_lbl(const char* value, size_t size) {
  lbl_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:MicroWireless.OneM2M.pb.FilterCriteria.lbl)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
FilterCriteria::lbl() const {
  // @@protoc_insertion_point(field_list:MicroWireless.OneM2M.pb.FilterCriteria.lbl)
  return lbl_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
FilterCriteria::mutable_lbl() {
  // @@protoc_insertion_point(field_mutable_list:MicroWireless.OneM2M.pb.FilterCriteria.lbl)
  return &lbl_;
}

// repeated .MicroWireless.OneM2M.pb.CommonTypes.ResourceType rty = 10;
inline int FilterCriteria::rty_size() const {
  return rty_.size();
}
inline void FilterCriteria::clear_rty() {
  rty_.Clear();
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_ResourceType FilterCriteria::rty(int index) const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.rty)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_ResourceType >(rty_.Get(index));
}
inline void FilterCriteria::set_rty(int index, ::MicroWireless::OneM2M::pb::CommonTypes_ResourceType value) {
  rty_.Set(index, value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.FilterCriteria.rty)
}
inline void FilterCriteria::add_rty(::MicroWireless::OneM2M::pb::CommonTypes_ResourceType value) {
  rty_.Add(value);
  // @@protoc_insertion_point(field_add:MicroWireless.OneM2M.pb.FilterCriteria.rty)
}
inline const ::google::protobuf::RepeatedField<int>&
FilterCriteria::rty() const {
  // @@protoc_insertion_point(field_list:MicroWireless.OneM2M.pb.FilterCriteria.rty)
  return rty_;
}
inline ::google::protobuf::RepeatedField<int>*
FilterCriteria::mutable_rty() {
  // @@protoc_insertion_point(field_mutable_list:MicroWireless.OneM2M.pb.FilterCriteria.rty)
  return &rty_;
}

// optional uint64 sza = 11;
inline void FilterCriteria::clear_sza() {
  sza_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 FilterCriteria::sza() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.sza)
  return sza_;
}
inline void FilterCriteria::set_sza(::google::protobuf::uint64 value) {
  
  sza_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.FilterCriteria.sza)
}

// optional uint64 szb = 12;
inline void FilterCriteria::clear_szb() {
  szb_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 FilterCriteria::szb() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.szb)
  return szb_;
}
inline void FilterCriteria::set_szb(::google::protobuf::uint64 value) {
  
  szb_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.FilterCriteria.szb)
}

// repeated .MicroWireless.OneM2M.pb.CommonTypes.ContentType cty = 13;
inline int FilterCriteria::cty_size() const {
  return cty_.size();
}
inline void FilterCriteria::clear_cty() {
  cty_.Clear();
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_ContentType FilterCriteria::cty(int index) const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.cty)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_ContentType >(cty_.Get(index));
}
inline void FilterCriteria::set_cty(int index, ::MicroWireless::OneM2M::pb::CommonTypes_ContentType value) {
  cty_.Set(index, value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.FilterCriteria.cty)
}
inline void FilterCriteria::add_cty(::MicroWireless::OneM2M::pb::CommonTypes_ContentType value) {
  cty_.Add(value);
  // @@protoc_insertion_point(field_add:MicroWireless.OneM2M.pb.FilterCriteria.cty)
}
inline const ::google::protobuf::RepeatedField<int>&
FilterCriteria::cty() const {
  // @@protoc_insertion_point(field_list:MicroWireless.OneM2M.pb.FilterCriteria.cty)
  return cty_;
}
inline ::google::protobuf::RepeatedField<int>*
FilterCriteria::mutable_cty() {
  // @@protoc_insertion_point(field_mutable_list:MicroWireless.OneM2M.pb.FilterCriteria.cty)
  return &cty_;
}

// repeated .MicroWireless.OneM2M.pb.Attribute atr = 14;
inline int FilterCriteria::atr_size() const {
  return atr_.size();
}
inline void FilterCriteria::clear_atr() {
  atr_.Clear();
}
inline const ::MicroWireless::OneM2M::pb::Attribute& FilterCriteria::atr(int index) const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.atr)
  return atr_.Get(index);
}
inline ::MicroWireless::OneM2M::pb::Attribute* FilterCriteria::mutable_atr(int index) {
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.FilterCriteria.atr)
  return atr_.Mutable(index);
}
inline ::MicroWireless::OneM2M::pb::Attribute* FilterCriteria::add_atr() {
  // @@protoc_insertion_point(field_add:MicroWireless.OneM2M.pb.FilterCriteria.atr)
  return atr_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MicroWireless::OneM2M::pb::Attribute >&
FilterCriteria::atr() const {
  // @@protoc_insertion_point(field_list:MicroWireless.OneM2M.pb.FilterCriteria.atr)
  return atr_;
}
inline ::google::protobuf::RepeatedPtrField< ::MicroWireless::OneM2M::pb::Attribute >*
FilterCriteria::mutable_atr() {
  // @@protoc_insertion_point(field_mutable_list:MicroWireless.OneM2M.pb.FilterCriteria.atr)
  return &atr_;
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.FilterUsage fu = 15;
inline void FilterCriteria::clear_fu() {
  fu_ = 0;
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_FilterUsage FilterCriteria::fu() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.fu)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_FilterUsage >(fu_);
}
inline void FilterCriteria::set_fu(::MicroWireless::OneM2M::pb::CommonTypes_FilterUsage value) {
  
  fu_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.FilterCriteria.fu)
}

// optional uint32 lim = 16;
inline void FilterCriteria::clear_lim() {
  lim_ = 0u;
}
inline ::google::protobuf::uint32 FilterCriteria::lim() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.FilterCriteria.lim)
  return lim_;
}
inline void FilterCriteria::set_lim(::google::protobuf::uint32 value) {
  
  lim_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.FilterCriteria.lim)
}

// -------------------------------------------------------------------

// Request

// optional .MicroWireless.OneM2M.pb.CommonTypes.Operation op = 1;
inline void Request::clear_op() {
  op_ = 0;
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_Operation Request::op() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.op)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_Operation >(op_);
}
inline void Request::set_op(::MicroWireless::OneM2M::pb::CommonTypes_Operation value) {
  
  op_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.op)
}

// optional string to = 2;
inline void Request::clear_to() {
  to_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Request::to() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.to)
  return to_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_to(const ::std::string& value) {
  
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.to)
}
inline void Request::set_to(const char* value) {
  
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.Request.to)
}
inline void Request::set_to(const char* value, size_t size) {
  
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.Request.to)
}
inline ::std::string* Request::mutable_to() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.to)
  return to_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request::release_to() {
  
  return to_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_to(::std::string* to) {
  if (to != NULL) {
    
  } else {
    
  }
  to_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), to);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.to)
}

// optional string fr = 3;
inline void Request::clear_fr() {
  fr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Request::fr() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.fr)
  return fr_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_fr(const ::std::string& value) {
  
  fr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.fr)
}
inline void Request::set_fr(const char* value) {
  
  fr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.Request.fr)
}
inline void Request::set_fr(const char* value, size_t size) {
  
  fr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.Request.fr)
}
inline ::std::string* Request::mutable_fr() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.fr)
  return fr_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request::release_fr() {
  
  return fr_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_fr(::std::string* fr) {
  if (fr != NULL) {
    
  } else {
    
  }
  fr_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fr);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.fr)
}

// optional string rqi = 4;
inline void Request::clear_rqi() {
  rqi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Request::rqi() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.rqi)
  return rqi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_rqi(const ::std::string& value) {
  
  rqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.rqi)
}
inline void Request::set_rqi(const char* value) {
  
  rqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.Request.rqi)
}
inline void Request::set_rqi(const char* value, size_t size) {
  
  rqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.Request.rqi)
}
inline ::std::string* Request::mutable_rqi() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.rqi)
  return rqi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request::release_rqi() {
  
  return rqi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_rqi(::std::string* rqi) {
  if (rqi != NULL) {
    
  } else {
    
  }
  rqi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rqi);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.rqi)
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.ResourceType ty = 5;
inline void Request::clear_ty() {
  ty_ = 0;
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_ResourceType Request::ty() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.ty)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_ResourceType >(ty_);
}
inline void Request::set_ty(::MicroWireless::OneM2M::pb::CommonTypes_ResourceType value) {
  
  ty_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.ty)
}

// optional string nm = 6;
inline void Request::clear_nm() {
  nm_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Request::nm() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.nm)
  return nm_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_nm(const ::std::string& value) {
  
  nm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.nm)
}
inline void Request::set_nm(const char* value) {
  
  nm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.Request.nm)
}
inline void Request::set_nm(const char* value, size_t size) {
  
  nm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.Request.nm)
}
inline ::std::string* Request::mutable_nm() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.nm)
  return nm_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request::release_nm() {
  
  return nm_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_nm(::std::string* nm) {
  if (nm != NULL) {
    
  } else {
    
  }
  nm_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nm);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.nm)
}

// optional string pc = 7;
inline void Request::clear_pc() {
  pc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Request::pc() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.pc)
  return pc_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_pc(const ::std::string& value) {
  
  pc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.pc)
}
inline void Request::set_pc(const char* value) {
  
  pc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.Request.pc)
}
inline void Request::set_pc(const char* value, size_t size) {
  
  pc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.Request.pc)
}
inline ::std::string* Request::mutable_pc() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.pc)
  return pc_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request::release_pc() {
  
  return pc_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_pc(::std::string* pc) {
  if (pc != NULL) {
    
  } else {
    
  }
  pc_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pc);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.pc)
}

// optional .google.protobuf.Timestamp ot = 8;
inline bool Request::has_ot() const {
  return !_is_default_instance_ && ot_ != NULL;
}
inline void Request::clear_ot() {
  if (GetArenaNoVirtual() == NULL && ot_ != NULL) delete ot_;
  ot_ = NULL;
}
inline const ::google::protobuf::Timestamp& Request::ot() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.ot)
  return ot_ != NULL ? *ot_ : *default_instance_->ot_;
}
inline ::google::protobuf::Timestamp* Request::mutable_ot() {
  
  if (ot_ == NULL) {
    ot_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.ot)
  return ot_;
}
inline ::google::protobuf::Timestamp* Request::release_ot() {
  
  ::google::protobuf::Timestamp* temp = ot_;
  ot_ = NULL;
  return temp;
}
inline void Request::set_allocated_ot(::google::protobuf::Timestamp* ot) {
  delete ot_;
  ot_ = ot;
  if (ot) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.ot)
}

// optional .google.protobuf.Timestamp rqet = 9;
inline bool Request::has_rqet() const {
  return !_is_default_instance_ && rqet_ != NULL;
}
inline void Request::clear_rqet() {
  if (GetArenaNoVirtual() == NULL && rqet_ != NULL) delete rqet_;
  rqet_ = NULL;
}
inline const ::google::protobuf::Timestamp& Request::rqet() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.rqet)
  return rqet_ != NULL ? *rqet_ : *default_instance_->rqet_;
}
inline ::google::protobuf::Timestamp* Request::mutable_rqet() {
  
  if (rqet_ == NULL) {
    rqet_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.rqet)
  return rqet_;
}
inline ::google::protobuf::Timestamp* Request::release_rqet() {
  
  ::google::protobuf::Timestamp* temp = rqet_;
  rqet_ = NULL;
  return temp;
}
inline void Request::set_allocated_rqet(::google::protobuf::Timestamp* rqet) {
  delete rqet_;
  rqet_ = rqet;
  if (rqet) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.rqet)
}

// optional .google.protobuf.Timestamp rset = 10;
inline bool Request::has_rset() const {
  return !_is_default_instance_ && rset_ != NULL;
}
inline void Request::clear_rset() {
  if (GetArenaNoVirtual() == NULL && rset_ != NULL) delete rset_;
  rset_ = NULL;
}
inline const ::google::protobuf::Timestamp& Request::rset() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.rset)
  return rset_ != NULL ? *rset_ : *default_instance_->rset_;
}
inline ::google::protobuf::Timestamp* Request::mutable_rset() {
  
  if (rset_ == NULL) {
    rset_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.rset)
  return rset_;
}
inline ::google::protobuf::Timestamp* Request::release_rset() {
  
  ::google::protobuf::Timestamp* temp = rset_;
  rset_ = NULL;
  return temp;
}
inline void Request::set_allocated_rset(::google::protobuf::Timestamp* rset) {
  delete rset_;
  rset_ = rset;
  if (rset) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.rset)
}

// optional .google.protobuf.Duration oet = 11;
inline bool Request::has_oet() const {
  return !_is_default_instance_ && oet_ != NULL;
}
inline void Request::clear_oet() {
  if (GetArenaNoVirtual() == NULL && oet_ != NULL) delete oet_;
  oet_ = NULL;
}
inline const ::google::protobuf::Duration& Request::oet() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.oet)
  return oet_ != NULL ? *oet_ : *default_instance_->oet_;
}
inline ::google::protobuf::Duration* Request::mutable_oet() {
  
  if (oet_ == NULL) {
    oet_ = new ::google::protobuf::Duration;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.oet)
  return oet_;
}
inline ::google::protobuf::Duration* Request::release_oet() {
  
  ::google::protobuf::Duration* temp = oet_;
  oet_ = NULL;
  return temp;
}
inline void Request::set_allocated_oet(::google::protobuf::Duration* oet) {
  delete oet_;
  oet_ = oet;
  if (oet) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.oet)
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.ResponseType rt = 12;
inline void Request::clear_rt() {
  rt_ = 0;
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_ResponseType Request::rt() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.rt)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_ResponseType >(rt_);
}
inline void Request::set_rt(::MicroWireless::OneM2M::pb::CommonTypes_ResponseType value) {
  
  rt_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.rt)
}

// optional .google.protobuf.Duration rp = 13;
inline bool Request::has_rp() const {
  return !_is_default_instance_ && rp_ != NULL;
}
inline void Request::clear_rp() {
  if (GetArenaNoVirtual() == NULL && rp_ != NULL) delete rp_;
  rp_ = NULL;
}
inline const ::google::protobuf::Duration& Request::rp() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.rp)
  return rp_ != NULL ? *rp_ : *default_instance_->rp_;
}
inline ::google::protobuf::Duration* Request::mutable_rp() {
  
  if (rp_ == NULL) {
    rp_ = new ::google::protobuf::Duration;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.rp)
  return rp_;
}
inline ::google::protobuf::Duration* Request::release_rp() {
  
  ::google::protobuf::Duration* temp = rp_;
  rp_ = NULL;
  return temp;
}
inline void Request::set_allocated_rp(::google::protobuf::Duration* rp) {
  delete rp_;
  rp_ = rp;
  if (rp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.rp)
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.ResultContent rcn = 14;
inline void Request::clear_rcn() {
  rcn_ = 0;
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_ResultContent Request::rcn() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.rcn)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_ResultContent >(rcn_);
}
inline void Request::set_rcn(::MicroWireless::OneM2M::pb::CommonTypes_ResultContent value) {
  
  rcn_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.rcn)
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.EventCat ec = 15;
inline void Request::clear_ec() {
  ec_ = 0;
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_EventCat Request::ec() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.ec)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_EventCat >(ec_);
}
inline void Request::set_ec(::MicroWireless::OneM2M::pb::CommonTypes_EventCat value) {
  
  ec_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.ec)
}

// optional bool da = 16;
inline void Request::clear_da() {
  da_ = false;
}
inline bool Request::da() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.da)
  return da_;
}
inline void Request::set_da(bool value) {
  
  da_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.da)
}

// optional string gid = 17;
inline void Request::clear_gid() {
  gid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Request::gid() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.gid)
  return gid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_gid(const ::std::string& value) {
  
  gid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.gid)
}
inline void Request::set_gid(const char* value) {
  
  gid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.Request.gid)
}
inline void Request::set_gid(const char* value, size_t size) {
  
  gid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.Request.gid)
}
inline ::std::string* Request::mutable_gid() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.gid)
  return gid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request::release_gid() {
  
  return gid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_gid(::std::string* gid) {
  if (gid != NULL) {
    
  } else {
    
  }
  gid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gid);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.gid)
}

// optional .MicroWireless.OneM2M.pb.FilterCriteria fc = 18;
inline bool Request::has_fc() const {
  return !_is_default_instance_ && fc_ != NULL;
}
inline void Request::clear_fc() {
  if (GetArenaNoVirtual() == NULL && fc_ != NULL) delete fc_;
  fc_ = NULL;
}
inline const ::MicroWireless::OneM2M::pb::FilterCriteria& Request::fc() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.fc)
  return fc_ != NULL ? *fc_ : *default_instance_->fc_;
}
inline ::MicroWireless::OneM2M::pb::FilterCriteria* Request::mutable_fc() {
  
  if (fc_ == NULL) {
    fc_ = new ::MicroWireless::OneM2M::pb::FilterCriteria;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.Request.fc)
  return fc_;
}
inline ::MicroWireless::OneM2M::pb::FilterCriteria* Request::release_fc() {
  
  ::MicroWireless::OneM2M::pb::FilterCriteria* temp = fc_;
  fc_ = NULL;
  return temp;
}
inline void Request::set_allocated_fc(::MicroWireless::OneM2M::pb::FilterCriteria* fc) {
  delete fc_;
  fc_ = fc;
  if (fc) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.Request.fc)
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.DiscoveryResultType drt = 19;
inline void Request::clear_drt() {
  drt_ = 0;
}
inline ::MicroWireless::OneM2M::pb::CommonTypes_DiscoveryResultType Request::drt() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.Request.drt)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_DiscoveryResultType >(drt_);
}
inline void Request::set_drt(::MicroWireless::OneM2M::pb::CommonTypes_DiscoveryResultType value) {
  
  drt_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.Request.drt)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace OneM2M
}  // namespace MicroWireless

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Request_2eproto__INCLUDED
