// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestPrim.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RequestPrim.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MicroWireless {
namespace OneM2M {
namespace pb {

namespace {

const ::google::protobuf::Descriptor* RequestPrim_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RequestPrim_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_RequestPrim_2eproto() {
  protobuf_AddDesc_RequestPrim_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "RequestPrim.proto");
  GOOGLE_CHECK(file != NULL);
  RequestPrim_descriptor_ = file->message_type(0);
  static const int RequestPrim_offsets_[19] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, op_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, to_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, fr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, rqi_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, ty_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, nm_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, pc_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, ot_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, rqet_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, rset_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, oet_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, rt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, rp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, rcn_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, ec_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, da_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, gid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, fc_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, drt_),
  };
  RequestPrim_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RequestPrim_descriptor_,
      RequestPrim::default_instance_,
      RequestPrim_offsets_,
      -1,
      -1,
      -1,
      sizeof(RequestPrim),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RequestPrim, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_RequestPrim_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RequestPrim_descriptor_, &RequestPrim::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_RequestPrim_2eproto() {
  delete RequestPrim::default_instance_;
  delete RequestPrim_reflection_;
}

void protobuf_AddDesc_RequestPrim_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2ftimestamp_2eproto();
  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fduration_2eproto();
  ::MicroWireless::OneM2M::pb::protobuf_AddDesc_CommonTypes_2eproto();
  ::MicroWireless::OneM2M::pb::protobuf_AddDesc_FilterCriteria_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021RequestPrim.proto\022\027MicroWireless.OneM2"
    "M.pb\032\037google/protobuf/timestamp.proto\032\036g"
    "oogle/protobuf/duration.proto\032\021CommonTyp"
    "es.proto\032\024FilterCriteria.proto\"\351\005\n\013Reque"
    "stPrim\022:\n\002op\030\001 \001(\0162..MicroWireless.OneM2"
    "M.pb.CommonTypes.Operation\022\n\n\002to\030\002 \001(\t\022\n"
    "\n\002fr\030\003 \001(\t\022\013\n\003rqi\030\004 \001(\t\022F\n\002ty\030\005 \001(\0162:.Mi"
    "croWireless.OneM2M.pb.CommonTypes.Suppor"
    "tedResourceType\022\n\n\002nm\030\006 \001(\t\022\n\n\002pc\030\007 \001(\t\022"
    "&\n\002ot\030\010 \001(\0132\032.google.protobuf.Timestamp\022"
    "(\n\004rqet\030\t \001(\0132\032.google.protobuf.Timestam"
    "p\022(\n\004rset\030\n \001(\0132\032.google.protobuf.Timest"
    "amp\022&\n\003oet\030\013 \001(\0132\031.google.protobuf.Durat"
    "ion\022=\n\002rt\030\014 \001(\01621.MicroWireless.OneM2M.p"
    "b.CommonTypes.ResponseType\022%\n\002rp\030\r \001(\0132\031"
    ".google.protobuf.Duration\022\?\n\003rcn\030\016 \001(\01622"
    ".MicroWireless.OneM2M.pb.CommonTypes.Res"
    "ultContent\0229\n\002ec\030\017 \001(\0162-.MicroWireless.O"
    "neM2M.pb.CommonTypes.EventCat\022\n\n\002da\030\020 \001("
    "\010\022\013\n\003gid\030\021 \001(\t\0223\n\002fc\030\022 \001(\0132\'.MicroWirele"
    "ss.OneM2M.pb.FilterCriteria\022E\n\003drt\030\023 \001(\016"
    "28.MicroWireless.OneM2M.pb.CommonTypes.D"
    "iscoveryResultTypeb\006proto3", 906);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RequestPrim.proto", &protobuf_RegisterTypes);
  RequestPrim::default_instance_ = new RequestPrim();
  RequestPrim::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_RequestPrim_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_RequestPrim_2eproto {
  StaticDescriptorInitializer_RequestPrim_2eproto() {
    protobuf_AddDesc_RequestPrim_2eproto();
  }
} static_descriptor_initializer_RequestPrim_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int RequestPrim::kOpFieldNumber;
const int RequestPrim::kToFieldNumber;
const int RequestPrim::kFrFieldNumber;
const int RequestPrim::kRqiFieldNumber;
const int RequestPrim::kTyFieldNumber;
const int RequestPrim::kNmFieldNumber;
const int RequestPrim::kPcFieldNumber;
const int RequestPrim::kOtFieldNumber;
const int RequestPrim::kRqetFieldNumber;
const int RequestPrim::kRsetFieldNumber;
const int RequestPrim::kOetFieldNumber;
const int RequestPrim::kRtFieldNumber;
const int RequestPrim::kRpFieldNumber;
const int RequestPrim::kRcnFieldNumber;
const int RequestPrim::kEcFieldNumber;
const int RequestPrim::kDaFieldNumber;
const int RequestPrim::kGidFieldNumber;
const int RequestPrim::kFcFieldNumber;
const int RequestPrim::kDrtFieldNumber;
#endif  // !_MSC_VER

RequestPrim::RequestPrim()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MicroWireless.OneM2M.pb.RequestPrim)
}

void RequestPrim::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  ot_ = const_cast< ::google::protobuf::Timestamp*>(&::google::protobuf::Timestamp::default_instance());
  rqet_ = const_cast< ::google::protobuf::Timestamp*>(&::google::protobuf::Timestamp::default_instance());
  rset_ = const_cast< ::google::protobuf::Timestamp*>(&::google::protobuf::Timestamp::default_instance());
  oet_ = const_cast< ::google::protobuf::Duration*>(&::google::protobuf::Duration::default_instance());
  rp_ = const_cast< ::google::protobuf::Duration*>(&::google::protobuf::Duration::default_instance());
  fc_ = const_cast< ::MicroWireless::OneM2M::pb::FilterCriteria*>(&::MicroWireless::OneM2M::pb::FilterCriteria::default_instance());
}

RequestPrim::RequestPrim(const RequestPrim& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MicroWireless.OneM2M.pb.RequestPrim)
}

void RequestPrim::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  op_ = 0;
  to_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rqi_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ty_ = 0;
  nm_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pc_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ot_ = NULL;
  rqet_ = NULL;
  rset_ = NULL;
  oet_ = NULL;
  rt_ = 0;
  rp_ = NULL;
  rcn_ = 0;
  ec_ = 0;
  da_ = false;
  gid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fc_ = NULL;
  drt_ = 0;
}

RequestPrim::~RequestPrim() {
  // @@protoc_insertion_point(destructor:MicroWireless.OneM2M.pb.RequestPrim)
  SharedDtor();
}

void RequestPrim::SharedDtor() {
  to_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rqi_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nm_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pc_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  gid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete ot_;
    delete rqet_;
    delete rset_;
    delete oet_;
    delete rp_;
    delete fc_;
  }
}

void RequestPrim::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RequestPrim::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RequestPrim_descriptor_;
}

const RequestPrim& RequestPrim::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_RequestPrim_2eproto();
  return *default_instance_;
}

RequestPrim* RequestPrim::default_instance_ = NULL;

RequestPrim* RequestPrim::New(::google::protobuf::Arena* arena) const {
  RequestPrim* n = new RequestPrim;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RequestPrim::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<RequestPrim*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(op_, ty_);
  to_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rqi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nm_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && ot_ != NULL) delete ot_;
  ot_ = NULL;
  ZR_(rt_, da_);
  if (GetArenaNoVirtual() == NULL && rqet_ != NULL) delete rqet_;
  rqet_ = NULL;
  if (GetArenaNoVirtual() == NULL && rset_ != NULL) delete rset_;
  rset_ = NULL;
  if (GetArenaNoVirtual() == NULL && oet_ != NULL) delete oet_;
  oet_ = NULL;
  if (GetArenaNoVirtual() == NULL && rp_ != NULL) delete rp_;
  rp_ = NULL;
  gid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && fc_ != NULL) delete fc_;
  fc_ = NULL;
  drt_ = 0;

#undef ZR_HELPER_
#undef ZR_

}

bool RequestPrim::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MicroWireless.OneM2M.pb.RequestPrim)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MicroWireless.OneM2M.pb.CommonTypes.Operation op = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_op(static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_Operation >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_to;
        break;
      }

      // optional string to = 2;
      case 2: {
        if (tag == 18) {
         parse_to:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_to()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->to().data(), this->to().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MicroWireless.OneM2M.pb.RequestPrim.to");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_fr;
        break;
      }

      // optional string fr = 3;
      case 3: {
        if (tag == 26) {
         parse_fr:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fr()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->fr().data(), this->fr().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MicroWireless.OneM2M.pb.RequestPrim.fr");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_rqi;
        break;
      }

      // optional string rqi = 4;
      case 4: {
        if (tag == 34) {
         parse_rqi:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_rqi()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->rqi().data(), this->rqi().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MicroWireless.OneM2M.pb.RequestPrim.rqi");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_ty;
        break;
      }

      // optional .MicroWireless.OneM2M.pb.CommonTypes.SupportedResourceType ty = 5;
      case 5: {
        if (tag == 40) {
         parse_ty:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_ty(static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_SupportedResourceType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_nm;
        break;
      }

      // optional string nm = 6;
      case 6: {
        if (tag == 50) {
         parse_nm:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nm()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->nm().data(), this->nm().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MicroWireless.OneM2M.pb.RequestPrim.nm");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_pc;
        break;
      }

      // optional string pc = 7;
      case 7: {
        if (tag == 58) {
         parse_pc:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pc()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->pc().data(), this->pc().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MicroWireless.OneM2M.pb.RequestPrim.pc");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_ot;
        break;
      }

      // optional .google.protobuf.Timestamp ot = 8;
      case 8: {
        if (tag == 66) {
         parse_ot:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ot()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_rqet;
        break;
      }

      // optional .google.protobuf.Timestamp rqet = 9;
      case 9: {
        if (tag == 74) {
         parse_rqet:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rqet()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_rset;
        break;
      }

      // optional .google.protobuf.Timestamp rset = 10;
      case 10: {
        if (tag == 82) {
         parse_rset:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rset()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_oet;
        break;
      }

      // optional .google.protobuf.Duration oet = 11;
      case 11: {
        if (tag == 90) {
         parse_oet:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_oet()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(96)) goto parse_rt;
        break;
      }

      // optional .MicroWireless.OneM2M.pb.CommonTypes.ResponseType rt = 12;
      case 12: {
        if (tag == 96) {
         parse_rt:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_rt(static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_ResponseType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(106)) goto parse_rp;
        break;
      }

      // optional .google.protobuf.Duration rp = 13;
      case 13: {
        if (tag == 106) {
         parse_rp:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rp()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(112)) goto parse_rcn;
        break;
      }

      // optional .MicroWireless.OneM2M.pb.CommonTypes.ResultContent rcn = 14;
      case 14: {
        if (tag == 112) {
         parse_rcn:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_rcn(static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_ResultContent >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(120)) goto parse_ec;
        break;
      }

      // optional .MicroWireless.OneM2M.pb.CommonTypes.EventCat ec = 15;
      case 15: {
        if (tag == 120) {
         parse_ec:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_ec(static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_EventCat >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(128)) goto parse_da;
        break;
      }

      // optional bool da = 16;
      case 16: {
        if (tag == 128) {
         parse_da:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &da_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(138)) goto parse_gid;
        break;
      }

      // optional string gid = 17;
      case 17: {
        if (tag == 138) {
         parse_gid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_gid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->gid().data(), this->gid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MicroWireless.OneM2M.pb.RequestPrim.gid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(146)) goto parse_fc;
        break;
      }

      // optional .MicroWireless.OneM2M.pb.FilterCriteria fc = 18;
      case 18: {
        if (tag == 146) {
         parse_fc:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_fc()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(152)) goto parse_drt;
        break;
      }

      // optional .MicroWireless.OneM2M.pb.CommonTypes.DiscoveryResultType drt = 19;
      case 19: {
        if (tag == 152) {
         parse_drt:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_drt(static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_DiscoveryResultType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MicroWireless.OneM2M.pb.RequestPrim)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MicroWireless.OneM2M.pb.RequestPrim)
  return false;
#undef DO_
}

void RequestPrim::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MicroWireless.OneM2M.pb.RequestPrim)
  // optional .MicroWireless.OneM2M.pb.CommonTypes.Operation op = 1;
  if (this->op() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->op(), output);
  }

  // optional string to = 2;
  if (this->to().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->to().data(), this->to().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.to");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->to(), output);
  }

  // optional string fr = 3;
  if (this->fr().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->fr().data(), this->fr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.fr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->fr(), output);
  }

  // optional string rqi = 4;
  if (this->rqi().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->rqi().data(), this->rqi().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.rqi");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->rqi(), output);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.SupportedResourceType ty = 5;
  if (this->ty() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->ty(), output);
  }

  // optional string nm = 6;
  if (this->nm().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->nm().data(), this->nm().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.nm");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->nm(), output);
  }

  // optional string pc = 7;
  if (this->pc().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->pc().data(), this->pc().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.pc");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->pc(), output);
  }

  // optional .google.protobuf.Timestamp ot = 8;
  if (this->has_ot()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, *this->ot_, output);
  }

  // optional .google.protobuf.Timestamp rqet = 9;
  if (this->has_rqet()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, *this->rqet_, output);
  }

  // optional .google.protobuf.Timestamp rset = 10;
  if (this->has_rset()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, *this->rset_, output);
  }

  // optional .google.protobuf.Duration oet = 11;
  if (this->has_oet()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, *this->oet_, output);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.ResponseType rt = 12;
  if (this->rt() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      12, this->rt(), output);
  }

  // optional .google.protobuf.Duration rp = 13;
  if (this->has_rp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, *this->rp_, output);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.ResultContent rcn = 14;
  if (this->rcn() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      14, this->rcn(), output);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.EventCat ec = 15;
  if (this->ec() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      15, this->ec(), output);
  }

  // optional bool da = 16;
  if (this->da() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(16, this->da(), output);
  }

  // optional string gid = 17;
  if (this->gid().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->gid().data(), this->gid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.gid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      17, this->gid(), output);
  }

  // optional .MicroWireless.OneM2M.pb.FilterCriteria fc = 18;
  if (this->has_fc()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      18, *this->fc_, output);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.DiscoveryResultType drt = 19;
  if (this->drt() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      19, this->drt(), output);
  }

  // @@protoc_insertion_point(serialize_end:MicroWireless.OneM2M.pb.RequestPrim)
}

::google::protobuf::uint8* RequestPrim::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MicroWireless.OneM2M.pb.RequestPrim)
  // optional .MicroWireless.OneM2M.pb.CommonTypes.Operation op = 1;
  if (this->op() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->op(), target);
  }

  // optional string to = 2;
  if (this->to().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->to().data(), this->to().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.to");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->to(), target);
  }

  // optional string fr = 3;
  if (this->fr().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->fr().data(), this->fr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.fr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->fr(), target);
  }

  // optional string rqi = 4;
  if (this->rqi().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->rqi().data(), this->rqi().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.rqi");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->rqi(), target);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.SupportedResourceType ty = 5;
  if (this->ty() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->ty(), target);
  }

  // optional string nm = 6;
  if (this->nm().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->nm().data(), this->nm().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.nm");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->nm(), target);
  }

  // optional string pc = 7;
  if (this->pc().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->pc().data(), this->pc().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.pc");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->pc(), target);
  }

  // optional .google.protobuf.Timestamp ot = 8;
  if (this->has_ot()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        8, *this->ot_, target);
  }

  // optional .google.protobuf.Timestamp rqet = 9;
  if (this->has_rqet()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        9, *this->rqet_, target);
  }

  // optional .google.protobuf.Timestamp rset = 10;
  if (this->has_rset()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        10, *this->rset_, target);
  }

  // optional .google.protobuf.Duration oet = 11;
  if (this->has_oet()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        11, *this->oet_, target);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.ResponseType rt = 12;
  if (this->rt() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      12, this->rt(), target);
  }

  // optional .google.protobuf.Duration rp = 13;
  if (this->has_rp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        13, *this->rp_, target);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.ResultContent rcn = 14;
  if (this->rcn() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      14, this->rcn(), target);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.EventCat ec = 15;
  if (this->ec() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      15, this->ec(), target);
  }

  // optional bool da = 16;
  if (this->da() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(16, this->da(), target);
  }

  // optional string gid = 17;
  if (this->gid().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->gid().data(), this->gid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MicroWireless.OneM2M.pb.RequestPrim.gid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        17, this->gid(), target);
  }

  // optional .MicroWireless.OneM2M.pb.FilterCriteria fc = 18;
  if (this->has_fc()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        18, *this->fc_, target);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.DiscoveryResultType drt = 19;
  if (this->drt() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      19, this->drt(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MicroWireless.OneM2M.pb.RequestPrim)
  return target;
}

int RequestPrim::ByteSize() const {
  int total_size = 0;

  // optional .MicroWireless.OneM2M.pb.CommonTypes.Operation op = 1;
  if (this->op() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->op());
  }

  // optional string to = 2;
  if (this->to().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->to());
  }

  // optional string fr = 3;
  if (this->fr().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fr());
  }

  // optional string rqi = 4;
  if (this->rqi().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->rqi());
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.SupportedResourceType ty = 5;
  if (this->ty() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->ty());
  }

  // optional string nm = 6;
  if (this->nm().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nm());
  }

  // optional string pc = 7;
  if (this->pc().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->pc());
  }

  // optional .google.protobuf.Timestamp ot = 8;
  if (this->has_ot()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->ot_);
  }

  // optional .google.protobuf.Timestamp rqet = 9;
  if (this->has_rqet()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->rqet_);
  }

  // optional .google.protobuf.Timestamp rset = 10;
  if (this->has_rset()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->rset_);
  }

  // optional .google.protobuf.Duration oet = 11;
  if (this->has_oet()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->oet_);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.ResponseType rt = 12;
  if (this->rt() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->rt());
  }

  // optional .google.protobuf.Duration rp = 13;
  if (this->has_rp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->rp_);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.ResultContent rcn = 14;
  if (this->rcn() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->rcn());
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.EventCat ec = 15;
  if (this->ec() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->ec());
  }

  // optional bool da = 16;
  if (this->da() != 0) {
    total_size += 2 + 1;
  }

  // optional string gid = 17;
  if (this->gid().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->gid());
  }

  // optional .MicroWireless.OneM2M.pb.FilterCriteria fc = 18;
  if (this->has_fc()) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->fc_);
  }

  // optional .MicroWireless.OneM2M.pb.CommonTypes.DiscoveryResultType drt = 19;
  if (this->drt() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->drt());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RequestPrim::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const RequestPrim* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const RequestPrim>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RequestPrim::MergeFrom(const RequestPrim& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.op() != 0) {
    set_op(from.op());
  }
  if (from.to().size() > 0) {

    to_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.to_);
  }
  if (from.fr().size() > 0) {

    fr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fr_);
  }
  if (from.rqi().size() > 0) {

    rqi_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.rqi_);
  }
  if (from.ty() != 0) {
    set_ty(from.ty());
  }
  if (from.nm().size() > 0) {

    nm_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nm_);
  }
  if (from.pc().size() > 0) {

    pc_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pc_);
  }
  if (from.has_ot()) {
    mutable_ot()->::google::protobuf::Timestamp::MergeFrom(from.ot());
  }
  if (from.has_rqet()) {
    mutable_rqet()->::google::protobuf::Timestamp::MergeFrom(from.rqet());
  }
  if (from.has_rset()) {
    mutable_rset()->::google::protobuf::Timestamp::MergeFrom(from.rset());
  }
  if (from.has_oet()) {
    mutable_oet()->::google::protobuf::Duration::MergeFrom(from.oet());
  }
  if (from.rt() != 0) {
    set_rt(from.rt());
  }
  if (from.has_rp()) {
    mutable_rp()->::google::protobuf::Duration::MergeFrom(from.rp());
  }
  if (from.rcn() != 0) {
    set_rcn(from.rcn());
  }
  if (from.ec() != 0) {
    set_ec(from.ec());
  }
  if (from.da() != 0) {
    set_da(from.da());
  }
  if (from.gid().size() > 0) {

    gid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.gid_);
  }
  if (from.has_fc()) {
    mutable_fc()->::MicroWireless::OneM2M::pb::FilterCriteria::MergeFrom(from.fc());
  }
  if (from.drt() != 0) {
    set_drt(from.drt());
  }
}

void RequestPrim::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RequestPrim::CopyFrom(const RequestPrim& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestPrim::IsInitialized() const {

  return true;
}

void RequestPrim::Swap(RequestPrim* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RequestPrim::InternalSwap(RequestPrim* other) {
  std::swap(op_, other->op_);
  to_.Swap(&other->to_);
  fr_.Swap(&other->fr_);
  rqi_.Swap(&other->rqi_);
  std::swap(ty_, other->ty_);
  nm_.Swap(&other->nm_);
  pc_.Swap(&other->pc_);
  std::swap(ot_, other->ot_);
  std::swap(rqet_, other->rqet_);
  std::swap(rset_, other->rset_);
  std::swap(oet_, other->oet_);
  std::swap(rt_, other->rt_);
  std::swap(rp_, other->rp_);
  std::swap(rcn_, other->rcn_);
  std::swap(ec_, other->ec_);
  std::swap(da_, other->da_);
  gid_.Swap(&other->gid_);
  std::swap(fc_, other->fc_);
  std::swap(drt_, other->drt_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RequestPrim::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RequestPrim_descriptor_;
  metadata.reflection = RequestPrim_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RequestPrim

// optional .MicroWireless.OneM2M.pb.CommonTypes.Operation op = 1;
void RequestPrim::clear_op() {
  op_ = 0;
}
 ::MicroWireless::OneM2M::pb::CommonTypes_Operation RequestPrim::op() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.op)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_Operation >(op_);
}
 void RequestPrim::set_op(::MicroWireless::OneM2M::pb::CommonTypes_Operation value) {
  
  op_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.op)
}

// optional string to = 2;
void RequestPrim::clear_to() {
  to_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& RequestPrim::to() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.to)
  return to_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_to(const ::std::string& value) {
  
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.to)
}
 void RequestPrim::set_to(const char* value) {
  
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.RequestPrim.to)
}
 void RequestPrim::set_to(const char* value, size_t size) {
  
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.RequestPrim.to)
}
 ::std::string* RequestPrim::mutable_to() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.to)
  return to_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RequestPrim::release_to() {
  
  return to_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_allocated_to(::std::string* to) {
  if (to != NULL) {
    
  } else {
    
  }
  to_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), to);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.to)
}

// optional string fr = 3;
void RequestPrim::clear_fr() {
  fr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& RequestPrim::fr() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.fr)
  return fr_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_fr(const ::std::string& value) {
  
  fr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.fr)
}
 void RequestPrim::set_fr(const char* value) {
  
  fr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.RequestPrim.fr)
}
 void RequestPrim::set_fr(const char* value, size_t size) {
  
  fr_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.RequestPrim.fr)
}
 ::std::string* RequestPrim::mutable_fr() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.fr)
  return fr_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RequestPrim::release_fr() {
  
  return fr_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_allocated_fr(::std::string* fr) {
  if (fr != NULL) {
    
  } else {
    
  }
  fr_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fr);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.fr)
}

// optional string rqi = 4;
void RequestPrim::clear_rqi() {
  rqi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& RequestPrim::rqi() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.rqi)
  return rqi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_rqi(const ::std::string& value) {
  
  rqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.rqi)
}
 void RequestPrim::set_rqi(const char* value) {
  
  rqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.RequestPrim.rqi)
}
 void RequestPrim::set_rqi(const char* value, size_t size) {
  
  rqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.RequestPrim.rqi)
}
 ::std::string* RequestPrim::mutable_rqi() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.rqi)
  return rqi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RequestPrim::release_rqi() {
  
  return rqi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_allocated_rqi(::std::string* rqi) {
  if (rqi != NULL) {
    
  } else {
    
  }
  rqi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rqi);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.rqi)
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.SupportedResourceType ty = 5;
void RequestPrim::clear_ty() {
  ty_ = 0;
}
 ::MicroWireless::OneM2M::pb::CommonTypes_SupportedResourceType RequestPrim::ty() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.ty)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_SupportedResourceType >(ty_);
}
 void RequestPrim::set_ty(::MicroWireless::OneM2M::pb::CommonTypes_SupportedResourceType value) {
  
  ty_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.ty)
}

// optional string nm = 6;
void RequestPrim::clear_nm() {
  nm_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& RequestPrim::nm() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.nm)
  return nm_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_nm(const ::std::string& value) {
  
  nm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.nm)
}
 void RequestPrim::set_nm(const char* value) {
  
  nm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.RequestPrim.nm)
}
 void RequestPrim::set_nm(const char* value, size_t size) {
  
  nm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.RequestPrim.nm)
}
 ::std::string* RequestPrim::mutable_nm() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.nm)
  return nm_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RequestPrim::release_nm() {
  
  return nm_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_allocated_nm(::std::string* nm) {
  if (nm != NULL) {
    
  } else {
    
  }
  nm_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nm);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.nm)
}

// optional string pc = 7;
void RequestPrim::clear_pc() {
  pc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& RequestPrim::pc() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.pc)
  return pc_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_pc(const ::std::string& value) {
  
  pc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.pc)
}
 void RequestPrim::set_pc(const char* value) {
  
  pc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.RequestPrim.pc)
}
 void RequestPrim::set_pc(const char* value, size_t size) {
  
  pc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.RequestPrim.pc)
}
 ::std::string* RequestPrim::mutable_pc() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.pc)
  return pc_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RequestPrim::release_pc() {
  
  return pc_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_allocated_pc(::std::string* pc) {
  if (pc != NULL) {
    
  } else {
    
  }
  pc_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pc);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.pc)
}

// optional .google.protobuf.Timestamp ot = 8;
bool RequestPrim::has_ot() const {
  return !_is_default_instance_ && ot_ != NULL;
}
void RequestPrim::clear_ot() {
  if (GetArenaNoVirtual() == NULL && ot_ != NULL) delete ot_;
  ot_ = NULL;
}
 const ::google::protobuf::Timestamp& RequestPrim::ot() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.ot)
  return ot_ != NULL ? *ot_ : *default_instance_->ot_;
}
 ::google::protobuf::Timestamp* RequestPrim::mutable_ot() {
  
  if (ot_ == NULL) {
    ot_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.ot)
  return ot_;
}
 ::google::protobuf::Timestamp* RequestPrim::release_ot() {
  
  ::google::protobuf::Timestamp* temp = ot_;
  ot_ = NULL;
  return temp;
}
 void RequestPrim::set_allocated_ot(::google::protobuf::Timestamp* ot) {
  delete ot_;
  ot_ = ot;
  if (ot) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.ot)
}

// optional .google.protobuf.Timestamp rqet = 9;
bool RequestPrim::has_rqet() const {
  return !_is_default_instance_ && rqet_ != NULL;
}
void RequestPrim::clear_rqet() {
  if (GetArenaNoVirtual() == NULL && rqet_ != NULL) delete rqet_;
  rqet_ = NULL;
}
 const ::google::protobuf::Timestamp& RequestPrim::rqet() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.rqet)
  return rqet_ != NULL ? *rqet_ : *default_instance_->rqet_;
}
 ::google::protobuf::Timestamp* RequestPrim::mutable_rqet() {
  
  if (rqet_ == NULL) {
    rqet_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.rqet)
  return rqet_;
}
 ::google::protobuf::Timestamp* RequestPrim::release_rqet() {
  
  ::google::protobuf::Timestamp* temp = rqet_;
  rqet_ = NULL;
  return temp;
}
 void RequestPrim::set_allocated_rqet(::google::protobuf::Timestamp* rqet) {
  delete rqet_;
  rqet_ = rqet;
  if (rqet) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.rqet)
}

// optional .google.protobuf.Timestamp rset = 10;
bool RequestPrim::has_rset() const {
  return !_is_default_instance_ && rset_ != NULL;
}
void RequestPrim::clear_rset() {
  if (GetArenaNoVirtual() == NULL && rset_ != NULL) delete rset_;
  rset_ = NULL;
}
 const ::google::protobuf::Timestamp& RequestPrim::rset() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.rset)
  return rset_ != NULL ? *rset_ : *default_instance_->rset_;
}
 ::google::protobuf::Timestamp* RequestPrim::mutable_rset() {
  
  if (rset_ == NULL) {
    rset_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.rset)
  return rset_;
}
 ::google::protobuf::Timestamp* RequestPrim::release_rset() {
  
  ::google::protobuf::Timestamp* temp = rset_;
  rset_ = NULL;
  return temp;
}
 void RequestPrim::set_allocated_rset(::google::protobuf::Timestamp* rset) {
  delete rset_;
  rset_ = rset;
  if (rset) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.rset)
}

// optional .google.protobuf.Duration oet = 11;
bool RequestPrim::has_oet() const {
  return !_is_default_instance_ && oet_ != NULL;
}
void RequestPrim::clear_oet() {
  if (GetArenaNoVirtual() == NULL && oet_ != NULL) delete oet_;
  oet_ = NULL;
}
 const ::google::protobuf::Duration& RequestPrim::oet() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.oet)
  return oet_ != NULL ? *oet_ : *default_instance_->oet_;
}
 ::google::protobuf::Duration* RequestPrim::mutable_oet() {
  
  if (oet_ == NULL) {
    oet_ = new ::google::protobuf::Duration;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.oet)
  return oet_;
}
 ::google::protobuf::Duration* RequestPrim::release_oet() {
  
  ::google::protobuf::Duration* temp = oet_;
  oet_ = NULL;
  return temp;
}
 void RequestPrim::set_allocated_oet(::google::protobuf::Duration* oet) {
  delete oet_;
  oet_ = oet;
  if (oet) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.oet)
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.ResponseType rt = 12;
void RequestPrim::clear_rt() {
  rt_ = 0;
}
 ::MicroWireless::OneM2M::pb::CommonTypes_ResponseType RequestPrim::rt() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.rt)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_ResponseType >(rt_);
}
 void RequestPrim::set_rt(::MicroWireless::OneM2M::pb::CommonTypes_ResponseType value) {
  
  rt_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.rt)
}

// optional .google.protobuf.Duration rp = 13;
bool RequestPrim::has_rp() const {
  return !_is_default_instance_ && rp_ != NULL;
}
void RequestPrim::clear_rp() {
  if (GetArenaNoVirtual() == NULL && rp_ != NULL) delete rp_;
  rp_ = NULL;
}
 const ::google::protobuf::Duration& RequestPrim::rp() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.rp)
  return rp_ != NULL ? *rp_ : *default_instance_->rp_;
}
 ::google::protobuf::Duration* RequestPrim::mutable_rp() {
  
  if (rp_ == NULL) {
    rp_ = new ::google::protobuf::Duration;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.rp)
  return rp_;
}
 ::google::protobuf::Duration* RequestPrim::release_rp() {
  
  ::google::protobuf::Duration* temp = rp_;
  rp_ = NULL;
  return temp;
}
 void RequestPrim::set_allocated_rp(::google::protobuf::Duration* rp) {
  delete rp_;
  rp_ = rp;
  if (rp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.rp)
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.ResultContent rcn = 14;
void RequestPrim::clear_rcn() {
  rcn_ = 0;
}
 ::MicroWireless::OneM2M::pb::CommonTypes_ResultContent RequestPrim::rcn() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.rcn)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_ResultContent >(rcn_);
}
 void RequestPrim::set_rcn(::MicroWireless::OneM2M::pb::CommonTypes_ResultContent value) {
  
  rcn_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.rcn)
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.EventCat ec = 15;
void RequestPrim::clear_ec() {
  ec_ = 0;
}
 ::MicroWireless::OneM2M::pb::CommonTypes_EventCat RequestPrim::ec() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.ec)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_EventCat >(ec_);
}
 void RequestPrim::set_ec(::MicroWireless::OneM2M::pb::CommonTypes_EventCat value) {
  
  ec_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.ec)
}

// optional bool da = 16;
void RequestPrim::clear_da() {
  da_ = false;
}
 bool RequestPrim::da() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.da)
  return da_;
}
 void RequestPrim::set_da(bool value) {
  
  da_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.da)
}

// optional string gid = 17;
void RequestPrim::clear_gid() {
  gid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& RequestPrim::gid() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.gid)
  return gid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_gid(const ::std::string& value) {
  
  gid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.gid)
}
 void RequestPrim::set_gid(const char* value) {
  
  gid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MicroWireless.OneM2M.pb.RequestPrim.gid)
}
 void RequestPrim::set_gid(const char* value, size_t size) {
  
  gid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MicroWireless.OneM2M.pb.RequestPrim.gid)
}
 ::std::string* RequestPrim::mutable_gid() {
  
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.gid)
  return gid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RequestPrim::release_gid() {
  
  return gid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RequestPrim::set_allocated_gid(::std::string* gid) {
  if (gid != NULL) {
    
  } else {
    
  }
  gid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gid);
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.gid)
}

// optional .MicroWireless.OneM2M.pb.FilterCriteria fc = 18;
bool RequestPrim::has_fc() const {
  return !_is_default_instance_ && fc_ != NULL;
}
void RequestPrim::clear_fc() {
  if (GetArenaNoVirtual() == NULL && fc_ != NULL) delete fc_;
  fc_ = NULL;
}
 const ::MicroWireless::OneM2M::pb::FilterCriteria& RequestPrim::fc() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.fc)
  return fc_ != NULL ? *fc_ : *default_instance_->fc_;
}
 ::MicroWireless::OneM2M::pb::FilterCriteria* RequestPrim::mutable_fc() {
  
  if (fc_ == NULL) {
    fc_ = new ::MicroWireless::OneM2M::pb::FilterCriteria;
  }
  // @@protoc_insertion_point(field_mutable:MicroWireless.OneM2M.pb.RequestPrim.fc)
  return fc_;
}
 ::MicroWireless::OneM2M::pb::FilterCriteria* RequestPrim::release_fc() {
  
  ::MicroWireless::OneM2M::pb::FilterCriteria* temp = fc_;
  fc_ = NULL;
  return temp;
}
 void RequestPrim::set_allocated_fc(::MicroWireless::OneM2M::pb::FilterCriteria* fc) {
  delete fc_;
  fc_ = fc;
  if (fc) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MicroWireless.OneM2M.pb.RequestPrim.fc)
}

// optional .MicroWireless.OneM2M.pb.CommonTypes.DiscoveryResultType drt = 19;
void RequestPrim::clear_drt() {
  drt_ = 0;
}
 ::MicroWireless::OneM2M::pb::CommonTypes_DiscoveryResultType RequestPrim::drt() const {
  // @@protoc_insertion_point(field_get:MicroWireless.OneM2M.pb.RequestPrim.drt)
  return static_cast< ::MicroWireless::OneM2M::pb::CommonTypes_DiscoveryResultType >(drt_);
}
 void RequestPrim::set_drt(::MicroWireless::OneM2M::pb::CommonTypes_DiscoveryResultType value) {
  
  drt_ = value;
  // @@protoc_insertion_point(field_set:MicroWireless.OneM2M.pb.RequestPrim.drt)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace OneM2M
}  // namespace MicroWireless

// @@protoc_insertion_point(global_scope)
